### ISSUE TITLE
Add markdown parsing

### ISSUE THREAD

**Issue by renestalder** [robinscholz/better-rest#10]
I think this plugin truly deserves its name for being a better rest API for Kirby. To be fair, there is not much of a use case to use the standard Kirby API, as it would require writing parsers for all the platforms that request content from the CMS (e.g. JavaScript, iOS, Android,...).

As it's obvious that Kirby is most likely used for the web and that when the API is used, it's consumed by the web platform and thus it makes sense to parse the content already to HTML, I believe that this plugin would fulfil the job even more by having the option to configure it to also parse the markdown parts of the content to HTML as well, or by doing that out of the box. As I don't really see the use case for having KirbyText parsed, but the markdown not.

While I saw in another issue that the argument against this is that this can easily be done on client-side (I agree with that), It's rather difficult for me to think of people consuming the API with KirbyText converted to HTML but without the markdown being converted. I kind of think it's either all (Better Rest plugin) or nothing (official API).

Would this be a big effort to add markdown to HTML conversion as a feature of this plugin?

Sadly, I'm not really into PHP programming and will not be able to contribute that part myself.

ps. I would even argue that the whole feature set of this plugin should be in the Kirby core, but here we are. You created the one plugin that makes Kirby relevant for decoupled and headless front-end development.

**Comment by robinscholz** [comment]
I’m afraid this is currently not possible. There is no way to control what content should get parsed and what content should not. When developing the plugin we tried implementing both kirbytext parsing and markdown parsing, but stopped when realising that every field with `type: text` or `type: textarea` would be affected. This essentially means that a lot of strings like titles, etc. get wrapped in a `<p>` tag which is not really desirable.

If you are after a plugin that’ll offer you a lot more fine-grained control, you might wanna check out [Kirby’s kql](https://github.com/getkirby/kql).
