### ISSUE TITLE
Documentation a bit unclear – how do I see this plugin taking effect?

### ISSUE THREAD

**Issue by Jones-S** [robinscholz/better-rest#4]
Hi there

I am sorry to bother you with this, but it seems that I have some issues with this plugin...
Maybe it is just an issue with unclear documentation 🤷‍♂ .

Anyway, as far as I understood, after installing this plugin (moving it to `site/plugins/`) I should see this having an effect right?

So by default it should convert kirbytags into HTML?
When running a normal REST API command with my application (in this case Insomnia) I still get bold parts in my richtext marked as \*\*bold\*\*.

What could be the reason?

Then I see that one can set a few settings within the `config/config.php`
I don't understand how I should prefix the settings
> All settings need to be prefixed with robinscholz.better-rest.!

Is it not enough to have `config.php` like:
```
return [
    'debug' => true,
    'smartypants' => true,
    'api' => [
        'slug' => 'api',
        'basicAuth' => true,
	'allowInsecure' => true,
    ],
    'srcset' => [333, 777, 888, 1111]
];
```

If I run the request again I don't see a source-set with these sizes. 
instead I see the srcset that was added by default (before installing this plugin)

```
"srcset": 
"http:\/\/cms.car.test\/media\/pages\/home\/2744598729-1583104264\/img-4166rrr-352x.jpg 352w, 
http:\/\/cms.car.test\/media\/pages\/home\/2744598729-1583104264\/img-4166rrr-864x.jpg 864w, 
http:\/\/cms.car.test\/media\/pages\/home\/2744598729-1583104264\/img-4166rrr-1408x.jpg 1408w"
```

I do not know where these sizes com from. 
Actually this is the first and only reason why I want to have this plugin,because I don't know how to get uploaded images in different sizes...

Also with using params like `api/pages/home?br-srcset=375,1200`. I don't see them having any effect...

Maybe you have some input on that.

Thank you in advance for your help.
I think some more examples would be helpful.

Cheers

**Comment by robinscholz** [comment]
Hi @Jones-S, it looks like you are querying the wrong endpoint. Instead of `/api`, try `/rest` in your requests. It should work fine then.

As for the `config.php`, this should work:

```
return [
    'debug' => true,
    'api' => [
        'slug' => 'api',
        'basicAuth' => true,
	'allowInsecure' => true,
    ],
    'robinscholz.better-rest.smartypants' => true,
    'robinscholz.better-rest.srcset' => [333, 777, 888, 1111]
];
```

**Comment by Jones-S** [comment]
Thank you for the comment. It makes things a lot clearer:
- It was unclear to me that even if I define `'slug' => 'api',` within the config that I can still access `/rest`. Also the prefixing of your settings is indicated, but I did not really get how to do that. So an example helps a lot.

I tried this with a simple page and I can access `/rest`.
What does not work so far is the smartypants to HTML.

This is my config now:

```
return [
  'debug' => true,
  'smartypants' => true, // https://getkirby.com/docs/guide/content/text-formatting#smartypants
  'api' => [
    'slug' => 'api',
    'basicAuth' => true,
    'allowInsecure' => true,
    'robinscholz.better-rest.smartypants' => true,
    'robinscholz.better-rest.srcset' => [333, 777, 888, 1111]
  ]
];
```

I tried to disable kirby's smartypants, but that did not help either.
My text is shown as:

```
"content": {
      "text": "What a **nice** day.",
      "title": "Home"
    },
```

Thanks for some more help in advance. Really appreciate it!

**Comment by robinscholz** [comment]
Closely compare my config syntax to yours again. The plugin settings need to be seperate from the kirby api settings.

**Comment by Jones-S** [comment]
Ooooh I see. Sorry about that. Second issue has the same thing in it.
Thank you for pointing it out 👍

**Comment by Jones-S** [comment]
Hm sorry, I still have a problem:

I get the english page with `'robinscholz.better-rest.language' => 'en'`
So I am assuming that your settings are working now.

What I still don't get is the better-rest smartypants

I have
```
return [
  'debug' => true,
  'languages' => true, // enable multilang
  // 'smartypants' => true, // https://getkirby.com/docs/guide/content/text-formatting#smartypants
  'api' => [
    'slug' => 'api',
    'basicAuth' => true,
    'allowInsecure' => true
  ],
  'robinscholz.better-rest.smartypants' => true,
  'robinscholz.better-rest.srcset' => [333, 777, 888, 1111],
  'robinscholz.better-rest.language' => 'en'
];
```

And my Textfield return values look like this:

```
"text": "You can define the columns that are shown in the table.\n\n**Bold-Test**\n\n*Italic-Test*\n\nThis is especially useful if you have a lot of fields in your structure.
```

Am I still missing something?

**Comment by Jones-S** [comment]
Oh I see the links `<a href="">` are working. Is this on purpose that you don't transform `*Italic*` and `**Bold**`?!

**Comment by robinscholz** [comment]
I think you are confusing smartypants and markdown parsing. You can read more about smartypants here: https://getkirby.com/docs/reference/system/options/smartypants

The plugin currently does not support markdown parsing, since this can easily be done client side.  Though I think adding it might not be too complex, might do so if I have some time.

**Comment by Jones-S** [comment]
Alright, I see. Yeah I included some markdown parsing yesterday. That was the way to go.
Ok now I think everythings clear.

thank you for all the help to a php/kirby noob. 👍 
Cheers
