### ISSUE TITLE
How to use Multilang? How to send an X-Language header?

### ISSUE THREAD

**Issue by Jones-S** [robinscholz/better-rest#6]
Sorry for another question:
https://github.com/robinscholz/better-rest#multilang

Here I read that I can request different languages, which is great.
Unfortunately I could not get it to work.

I tried:

```
return [
  'debug' => true,
  'languages' => true, // enable multilang
  'smartypants' => true, // https://getkirby.com/docs/guide/content/text-formatting#smartypants
  'api' => [
    'slug' => 'api',
    'basicAuth' => true,
    'allowInsecure' => true,
    'robinscholz.better-rest.smartypants' => true,
    'robinscholz.better-rest.srcset' => [333, 777, 888, 1111],
    'robinscholz.better-rest.language' => 'en'
```

Which did not have any effect. I would always just get the default language.
Just to be sure:

I would request a page just normally like:

`/rest/pages/home` and would get the english page, if that worked?

-------
I then tried to use an _X-Language header_.

Of which I've never heard.
I googled hard, but I could not really find any information for that...

I tried to send 

```
header('X-Language: en');
// or 
header('Accept-Language: en'); // because Accept-Language seems to be a header that is sometimes used, whereas X-Language does not really have any appearance within google...
// or
// both Language headers at the same time
header('Accept-Language: en');
header('Content-Language: en');
```

But nothing changes my result. Always German.

Sorry for those nooby PHP questions, but PHP is not the language I use that often.

Thank you for your help.
Cheers

**Comment by robinscholz** [comment]
Try the following config:

```
return [
  'debug' => true,
  'languages' => true, // enable multilang
  'api' => [
    'basicAuth' => true,
    'allowInsecure' => true
  ],
  'robinscholz.better-rest.smartypants' => true,
  'robinscholz.better-rest.srcset' => [333, 777, 888, 1111],
  'robinscholz.better-rest.language' => 'en'
```

The plugin settings need to be seperated from the kirby specific `api` settings. This should also return a response with values in english.

If you want to fetch another language you need to include `{ 'x-language': locale }` in your request. I guess in your case it might be `header('x-Language': 'de');` for example.
