### ISSUE TITLE
Date format is corrupted by non-breaking space

### ISSUE THREAD

**Issue by Jones-S** [robinscholz/better-rest#9]
Unfortunately the rest plugin does add a non-breaking space to a date field's return value:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/7059580/79686806-5d6bff80-8243-11ea-873e-66b4dd504ca3.png">

This `&#160;` is a non breaking space and it is not present if I access the endpoint without `/rest`
<img width="285" alt="image" src="https://user-images.githubusercontent.com/7059580/79686833-7ffe1880-8243-11ea-8b9f-d738237df32a.png">

Just to tell you. I guess this could be classified as bug.
cheers

**Comment by robinscholz** [comment]
@Jones-S Did you turn on smartypants parsing?

**Comment by Jones-S** [comment]
Yes I do. But even then, why would I want a normal space to be transformed into a non-breaking space? Is that what smartypants is supposed to do?

**Comment by Jones-S** [comment]
Oh I see:
> Replace existing spaces with non-break spaces for spaces used as a thousand separator and between a number and the unit symbol that follows it (for most common units).

https://michelf.ca/projects/php-smartypants/

I have to check if there is some configuration to smartypants, which could disable this...
